### ISSUE TITLE
Onlinejs not working

### ISSUE THREAD

**Issue by AliEsmaeilli** [PixelsCommander/OnlineJS#15]
Hi ,
We have used your library in our apps and as your library not working properly and return offline status our apps are all crashed  , Please check the plugin As soon as you can , I think it is something wrong with your domain : http://offlinejs.com/online.php

**Comment by PixelsCommander** [comment]
Hi Ali

I am working on fixing it. For your safety please set your own endpoint
this is described in
https://github.com/PixelsCommander/OnlineJS#safety-and-guarantees and takes
5-10 minutes.

2018-01-20 19:41 GMT+01:00 AliEsmaeilli <notifications@github.com>:

**Comment by AliEsmaeilli** [comment]
Hi , I really appreciate your efforts but I didn't pay attention to safety url .
Since our app is in wide use we cann't make any new updates . 
We really need your plugin to be worked and I beg to fix it please , It sometimes return true and sometimes false . 
It makes problems for me , Please review the bug and fix it  , kindly.
I really appreciate your help . 
Tnx.

**Comment by PixelsCommander** [comment]
It is not the bug in a code - it is server issue. When server is down lib
stops working. Not sure I can fix server stability asap just can restart it
every time it is stuck.

What we can do also is to point library to your server. Just shout me NS
server to point domain to and give me a promise it is up since now and you
understand responsibility.

2018-01-26 10:16 GMT+01:00 AliEsmaeilli <notifications@github.com>:

**Comment by ashrafiamir** [comment]
Hi
I have just Ali's problem 
I used your library and always have problems and it seems to be offline.
I have an application in publishing which I cannot update it.
Please solve this problem somehow, the users of our application are getting lost because of this problem.
It's disconnected most of the time in recent months and it gets connected sometimes 
It was disconnected yesterday 
Now it's ok please keep it in this condition not to be disconnected again.

**Comment by ashrafiamir** [comment]
I have this problem again
please help

**Comment by AliEsmaeilli** [comment]
Dear  @PixelsCommander ,
Please give me an email address so I can send you a NS of our server 
so you can use it to solve the problem with the plugin.
Thanks

**Comment by PixelsCommander** [comment]
denis.radin@gmail.com

2018-06-09 11:17 GMT+02:00 AliEsmaeilli <notifications@github.com>:

**Comment by AliEsmaeilli** [comment]
Hi @PixelsCommander 
Can you check your plugin server again ? 
It is not working thanks

**Comment by ashrafiamir** [comment]
Please
help
My problem is not resolved
I really need your help
My startup is failing
Because the application cannot be opened

**Comment by cotwitch** [comment]
@PixelCommander : You gave them a code for free. They complain. You gave them an endpoint. They complain. You gave them valuable advice. They complain. What more would you have to do to satisfy them?

**Comment by PixelsCommander** [comment]
@ashrafiamir solved, I moved server to another machine, should be better now
